version: '3'
services:
  # Nginxコンテナ定義
  web:
    build:
      context: ./nginx_docker
    volumes:
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
    ports:
      - 80:80
    depends_on:
      - app
  # Railsコンテナ定義
  app:
    build: .
    command: bundle exec puma -C config/puma.rb
    environment:
      - MYSQL_HOST=db
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - .:/run-share
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
      - log-data:/myapp/log
    depends_on:
      - db
    tty: true
    stdin_open: true
  # MySQLコンテナ定義
  db:
    image: mysql:5.6.51
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: root
    ports:
      - "4306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  public-data:
  tmp-data:
  log-data:
  mysql-data: