version: '3' #docker-composeのバージョン
services:
  # Railsコンテナ定義
  web:
    build: . # Dockerfileを使用してイメージをビルド
    # 前回サーバー起動時に作成されたserver.pidファイルを削除
    # コンテナ起動時のデフォルトコマンド
    # ポート番号：3000
    # バインドするIPアドレス：0.0.0.0
    # ポート3000が来たらrailsサーバーが応答
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - .:/run-share
    # コンテナの外部に3000番を公開
    # 公開するポート番号：コンテナ内部の転送先ポート番号
    ports:
      - 3000:3000
    depends_on:
      - db # dbコンテナが先に起動するよう設定
    tty: true
    stdin_open: true
  # MySQLコンテナ定義
  db:
    image: mysql:5.6.51 #既存アプリとあわせる。ターミナルに[$ mysql --version]で確認
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} # mysqlのルートユーザーのパスワード設定
      MYSQL_DATABASE: root
    ports:
      - "4306:3306"
    volumes:
      - mysql-data:/var/lib/mysql # ローカルで保持しているDBをコンテナにマウント
volumes:
  mysql-data: # DBの内容をローカルに保持